spring:
  application:
    name: gestao-acoes

  # ==========================================
  # CONFIGURAÇÕES DO LIQUIBASE (AULA 11)
  # ==========================================
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  # ==========================================
  # CONFIGURAÇÕES DO HIBERNATE / JPA
  # ==========================================
  jpa:
    hibernate:
      # O Hibernate NÃO cria tabelas mais. Ele apenas valida as do Liquibase.
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true