-- Criação da tabela de Corretoras
CREATE TABLE corretoras (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            cnpj VARCHAR(14) NOT NULL UNIQUE,
                            razao_social VARCHAR(255) NOT NULL,
                            nome_fantasia VARCHAR(255),
                            email VARCHAR(255),
                            telefone VARCHAR(50),
                            cep VARCHAR(8) NOT NULL,
                            logradouro VARCHAR(255) NOT NULL,
                            numero VARCHAR(50),
                            complemento VARCHAR(255),
                            bairro VARCHAR(255) NOT NULL,
                            cidade VARCHAR(255) NOT NULL,
                            uf VARCHAR(2) NOT NULL,
                            situacao_cadastral VARCHAR(50) NOT NULL,
                            status_cvm VARCHAR(50) NOT NULL,
                            data_hora_cadastro TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Criação da tabela de Ações
CREATE TABLE acoes (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       ticker VARCHAR(20) NOT NULL,
                       nome_empresa VARCHAR(255),
                       mercado VARCHAR(50) NOT NULL,
                       moeda VARCHAR(3) NOT NULL,
                       cotacao_atual DECIMAL(19, 4) NOT NULL,
                       data_hora_cotacao TIMESTAMP WITH TIME ZONE NOT NULL,
                       provedor_origem VARCHAR(100),
                       CONSTRAINT uk_acao_ticker_mercado UNIQUE (ticker, mercado)
);