CREATE TABLE posicoes (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          acao_id BIGINT NOT NULL UNIQUE,
                          quantidade INT NOT NULL,
                          preco_medio DECIMAL(19, 4) NOT NULL,
                          CONSTRAINT fk_posicao_acao FOREIGN KEY (acao_id) REFERENCES acoes (id)
);

CREATE TABLE transacoes (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            acao_id BIGINT NOT NULL,
                            corretora_id BIGINT NOT NULL,
                            tipo_transacao VARCHAR(10) NOT NULL,
                            quantidade INT NOT NULL,
                            valor_unitario DECIMAL(19, 4) NOT NULL,
                            data_hora_transacao TIMESTAMP WITH TIME ZONE NOT NULL,
                            CONSTRAINT fk_transacao_acao FOREIGN KEY (acao_id) REFERENCES acoes (id),
                            CONSTRAINT fk_transacao_corretora FOREIGN KEY (corretora_id) REFERENCES corretoras (id)
);